---
- name: Check for base system config lockfile
  stat: path="/mnt/.nvm_mountpoints"
  register: basic_config_lock
- import_tasks: filesystem.yml
  when: basic_config_lock.stat.exists == False or fs_reset is defined
- import_tasks: basic.yml
- import_tasks: packages.yml
- import_tasks: networking.yml
- import_tasks: kubernetes.yml
- import_tasks: nfs.yml
- import_tasks: fan-support.yml
  when: settings.pimoroni_fans_enabled == "enabled"
