- name: Reset Cluster
  block:
    - name: do cleanup
      ansible.builtin.shell:
        cmd: |
          kubeadm reset -f
          rm -f $HOME/.kube/config
          rm -rf /etc/kubernetes/*
          rm -rf /var/lib/docker/containers/*
          rm -rf /var/run/docker*
  rescue:
    - name: had some errors
      ansible.builtin.debug:
        msg: 'There were some errors during reset, ignoring'
  when: RESET is defined
    
- name: "Create kubernetes folders"
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    mode: 0640
    owner: root
    group: root

- name: "Push Kubernetes Master PKI files to master replicas"
  copy: 
    src: /tmp/kubeadm-ha/
    dest: /etc/kubernetes/
    owner: root
    group: root
    mode: preserve

- name: Generate master join token
  ansible.builtin.command: 
    cmd: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['primary_master'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Join Master replicas to cluster
  shell: "{{ kubeadm_join }} --control-plane"

- name: Create .kube folder
  file:
    path: "~{{ ansible_ssh_user }}/.kube"
    state: directory
    owner: "{{ ansible_ssh_user }}"

- name: Copy admin.conf to .kube folder
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "~{{ ansible_ssh_user }}/.kube/config"
    owner: "{{ ansible_ssh_user }}"
    remote_src: yes

- name: Copy calico yaml file
  copy:
    src: files/calico.yaml
    dest: /tmp/calico.yaml

- name: Create calico POD network
  ansible.builtin.shell:
    cmd: kubectl apply -f /tmp/calico.yaml
