---
- hosts: all
  vars:
    settings:
      nfs_host: domain.internal.martinescu.org
      nfs_multi_share_path: "/storage/k8s"
      pimoroni_fans_enabled: "disabled"
  roles:
    - common

- hosts: lb_nodes
  roles:
    - keepalived

- hosts: primary_master
  roles:
    - kubemaster

- hosts: other_masters
  roles:
    - kube-replica-master

- hosts: workers
  roles:
    - kubeworkers

- hosts: masters
  roles:
    - basics
